- grid/src/main/java/org/highfives/grid/work/command/aggregate/AdTime.java
- grid/src/main/java/org/highfives/grid/work/command/controller/AdTimeController.java
- grid/src/main/java/org/highfives/grid/work/command/dto/AdTimeDTO.java
- grid/src/main/java/org/highfives/grid/work/command/repository/AdTimeRepository.java
- grid/src/main/java/org/highfives/grid/work/command/service/AdTimeService.java
- grid/src/main/java/org/highfives/grid/work/command/service/AdTimeServiceImpl.java
- grid/src/main/java/org/highfives/grid/work/command/vo/ResponseAdTimeVO.java
- grid/src/main/java/org/highfives/grid/work/query/configuration/MybatisConfiguration.java
- grid/src/main/java/org/highfives/grid/work/query/controller/AdTimeController.java
- grid/src/main/java/org/highfives/grid/work/query/dto/AdTimeDTO.java
- grid/src/main/java/org/highfives/grid/work/query/repository/AdTimeMapper.java
- grid/src/main/java/org/highfives/grid/work/query/service/AdTimeService.java
- grid/src/main/java/org/highfives/grid/work/query/service/AdTimeServiceImpl.java
- grid/src/main/java/org/highfives/grid/work/query/vo/ResponseAdTimeListVO.java
- grid/src/main/resources/org/highfives/grid/work/query/repository/AdTimeMapper.xml
- grid/src/test/java/org/highfives/grid/work/command/service/AdTimeServiceImplTest.java
- grid/src/test/java/org/highfives/grid/work/query/service/AdTimeServiceImplTest.java
feature/ad-time -> develop
출퇴근 체크, 조회 기능 추가
main 브랜치에 있는 파일로 main과 합칠 때 충돌이 발생 할 것 같습니다.
> Feat: 출퇴근 기능 구현

- grid/src/main/java/org/highfives/grid/performance_review/query/aggregate/PerformanceReviewGoal.java
- grid/src/main/java/org/highfives/grid/performance_review/query/controller/PerformanceReviewGoalController.java
- grid/src/main/java/org/highfives/grid/performance_review/query/dto/ApproverDTO.java
- grid/src/main/java/org/highfives/grid/performance_review/query/dto/EmployeeDTO.java
- grid/src/main/java/org/highfives/grid/performance_review/query/dto/PerformanceReviewGoalDTO.java
- grid/src/main/java/org/highfives/grid/performance_review/query/dto/WriterDTO.java
- grid/src/main/java/org/highfives/grid/performance_review/query/repository/PerformanceReviewGoalMapper.java
- grid/src/main/java/org/highfives/grid/performance_review/query/service/PerformanceReviewGoalService.java
- grid/src/main/java/org/highfives/grid/performance_review/query/service/PerformanceReviewGoalServiceImpl.java
- grid/src/main/java/org/highfives/grid/performance_review/query/vo/ResponsePerformanceReviewGoalVO.java
- grid/src/main/resources/org/highfives/grid/performance_review/query/repository/PerformanceReviewGoalMapper.xml
- grid/src/test/java/org/highfives/grid/performance_review/query/service/PerformanceReviewGoalServiceImplTest.java
feature/performance-review-goal -> develop
- 작성자를 기준으로 평가 목표 목록 조회함
- 결재자를 기준으로 평가 목표 목록 조회함
- 평가 목표 상세 조회함
closed #63
employeeDTO는 차후 사용할수도 있음
- 작성자 기준 조회 결과
- 결재자 기준 조회 결과
- 평가 목표 상세 조회 결과
> Feat: 작성한 업적 평가 조회 기능 구현

- grid/src/main/java/org/highfives/grid/performance_review/command/aggregate/PerformanceReviewGoal.java
- grid/src/main/java/org/highfives/grid/performance_review/command/controller/PerformanceReviewGoalController.java
- grid/src/main/java/org/highfives/grid/performance_review/command/dto/PerformanceReviewGoalDTO.java
- grid/src/main/java/org/highfives/grid/performance_review/command/repository/PerformanceReviewGoalRepository.java
- grid/src/main/java/org/highfives/grid/performance_review/command/service/PerformanceReviewGoalService.java
- grid/src/main/java/org/highfives/grid/performance_review/command/service/PerformanceReviewGoalServiceImpl.java
- grid/src/main/java/org/highfives/grid/performance_review/command/vo/ResponsePerformanceReviewGoalVO.java
- grid/src/main/java/org/highfives/grid/performance_review/query/dto/DetailGoalDTO.java
- grid/src/main/java/org/highfives/grid/performance_review/query/dto/GoalItemDTO.java
- grid/src/main/java/org/highfives/grid/performance_review/query/vo/ResponseDetailGoalVO.java
- grid/src/test/java/org/highfives/grid/performance_review/command/service/PerformanceReviewGoalServiceImplTest.java
feature/performance-review-goal -> develop
업적 평가 목표 추가
#81
> Feat: 업적 평가 목표 추가 기능 

- grid/src/main/java/org/highfives/grid/vacation/query/controller/VacationController.java
- grid/src/main/java/org/highfives/grid/vacation/query/repository/VacationMapper.java
- grid/src/main/java/org/highfives/grid/vacation/query/service/VacationService.java
- grid/src/main/java/org/highfives/grid/vacation/query/service/VacationServiceImpl.java
- grid/src/main/java/org/highfives/grid/vacation/query/vo/DeptSearch.java
- grid/src/main/java/org/highfives/grid/vacation/query/vo/HistorySearch.java
- grid/src/main/java/org/highfives/grid/vacation/query/vo/NameSearch.java
- grid/src/main/resources/org/highfives/grid/vacation/query/repository/VacationMapper.xml
feature/vacation-search -> feature/vacation
이름으로 휴가정보 검색, 부서명으로 휴가정보 검색, 휴가이력 검색 기능 추가
#10 #75 
정상 작동
> Feat: 휴가관련 검색기능 추가

- grid/src/main/java/org/highfives/grid/user/controller/UserController.java
- grid/src/main/java/org/highfives/grid/user/entity/Employee.java
- grid/src/main/java/org/highfives/grid/user/repository/UserRepository.java
- grid/src/main/java/org/highfives/grid/user/service/UserService.java
- grid/src/main/java/org/highfives/grid/user/service/UserServiceImpl.java
- grid/src/main/java/org/highfives/grid/user/vo/UserAnnualResponse.java
- grid/src/main/java/org/highfives/grid/vacation/command/controller/VacationController.java
- grid/src/main/java/org/highfives/grid/vacation/command/entity/VacationType.java
- grid/src/main/java/org/highfives/grid/vacation/command/repository/VacationHistoryRepository.java
- grid/src/main/java/org/highfives/grid/vacation/command/repository/VacationInfoRepository.java
- grid/src/main/java/org/highfives/grid/vacation/command/repository/VacationTypeRepository.java
- grid/src/main/java/org/highfives/grid/vacation/command/service/VacationService.java
- grid/src/main/java/org/highfives/grid/vacation/command/service/VacationServiceImpl.java
- grid/src/main/java/org/highfives/grid/vacation/command/vo/GiveVacation.java
- grid/src/main/java/org/highfives/grid/vacation/command/vo/RegistVacationType.java
- grid/src/main/java/org/highfives/grid/vacation/query/controller/VacationController.java
- grid/src/main/java/org/highfives/grid/vacation/query/repository/VacationMapper.java
- grid/src/main/java/org/highfives/grid/vacation/query/service/VacationService.java
- grid/src/main/java/org/highfives/grid/vacation/query/service/VacationServiceImpl.java
- grid/src/main/java/org/highfives/grid/vacation/query/vo/DeptSearch.java
- grid/src/main/java/org/highfives/grid/vacation/query/vo/HistorySearch.java
- grid/src/main/java/org/highfives/grid/vacation/query/vo/NameSearch.java
- grid/src/main/resources/org/highfives/grid/vacation/query/repository/VacationMapper.xml
feature/vacation-registType -> feature/vacation
관리자가 휴가의 종류를 직접 등록하는 기능 추가 #73 
테스트 성공
> Feat: 휴가 종류 등록기능 추가

- grid/src/main/java/org/highfives/grid/approval/command/aggregate/OvertimeApproval.java
- grid/src/main/java/org/highfives/grid/approval/command/aggregate/OvertimeType.java
- grid/src/main/java/org/highfives/grid/approval/command/aggregate/RWApproval.java
- grid/src/main/java/org/highfives/grid/approval/command/controller/ApprovalController.java
- grid/src/main/java/org/highfives/grid/approval/command/repository/RWApprovalRepository.java
- grid/src/main/java/org/highfives/grid/approval/command/service/ApprovalService.java
- grid/src/main/java/org/highfives/grid/approval/command/service/ApprovalServiceImpl.java
- grid/src/main/java/org/highfives/grid/approval/command/vo/RWApprovalVO.java
- grid/src/main/java/org/highfives/grid/approval/command/vo/ResApprovalVO.java
- grid/src/main/java/org/highfives/grid/approval/common/dto/OvertimeApprovalDTO.java
- grid/src/main/java/org/highfives/grid/approval/common/dto/RWApprovalDTO.java
- grid/src/main/java/org/highfives/grid/approval/common/dto/RwApprovalDTO.java
- grid/src/main/java/org/highfives/grid/work/query/controller/RwApprovalController.java
- grid/src/main/java/org/highfives/grid/work/query/service/RwApprovalService.java
- grid/src/main/java/org/highfives/grid/work/query/service/RwApprovalServiceImpl.java
- grid/src/main/java/org/highfives/grid/work/query/vo/ResponseRwListVO.java
> Feat: 시간 외 근무 결재 관련 기능 구현

- grid/src/main/java/org/highfives/grid/performance_review/command/controller/PerformanceReviewGoalController.java
- grid/src/main/java/org/highfives/grid/performance_review/command/service/PerformanceReviewGoalService.java
- grid/src/main/java/org/highfives/grid/performance_review/command/service/PerformanceReviewGoalServiceImpl.java
- grid/src/test/java/org/highfives/grid/performance_review/command/service/PerformanceReviewGoalServiceImplTest.java
feature/performance-review-goal -> develop
- 확인 중, 승인, 반려 상태로 변경 
- 반려 상태일 때 작성, 상신 가능 
> Feat: 업적 평가 목표 상태 수정

- grid/src/main/java/org/highfives/grid/approval/command/aggregate/BTApproval.java
- grid/src/main/java/org/highfives/grid/approval/command/aggregate/OvertimeApproval.java
- grid/src/main/java/org/highfives/grid/approval/command/aggregate/RWApproval.java
- grid/src/main/java/org/highfives/grid/approval/command/controller/ApprovalController.java
- grid/src/main/java/org/highfives/grid/approval/command/service/ApprovalServiceImpl.java
- grid/src/main/java/org/highfives/grid/approval/command/vo/BTApprovalVO.java
- grid/src/main/java/org/highfives/grid/approval/command/vo/OvertimeApprovalVO.java
> Fix: 결재 관련 수정

- grid/src/main/java/org/highfives/grid/approval/command/service/ApprovalServiceImpl.java
- grid/src/main/java/org/highfives/grid/approval_chain/command/aggregate/OApprovalChain.java
- grid/src/main/java/org/highfives/grid/approval_chain/command/aggregate/RWApprovalChain.java
- grid/src/main/java/org/highfives/grid/approval_chain/command/repository/OApprovalChainRepository.java
- grid/src/main/java/org/highfives/grid/approval_chain/command/repository/RWApprovalChainRepository.java
- grid/src/main/java/org/highfives/grid/approval_chain/command/service/ApprovalChainService.java
- grid/src/main/java/org/highfives/grid/approval_chain/command/service/ApprovalChainServiceImpl.java
- grid/src/main/java/org/highfives/grid/approval_chain/common/dto/OApprovalChainDTO.java
- grid/src/main/java/org/highfives/grid/approval_chain/common/dto/RWApprovalChainDTO.java
- grid/src/main/resources/org/highfives/grid/approval_chain/query/repository/ApprovalChainMapper.xml
> Feat: 시간 외 근무 결재 라인 생성, 단축 근무 결재 라인 생성

- grid/src/main/java/org/highfives/grid/performance_review/query/aggregate/PerformanceReview.java
- grid/src/main/java/org/highfives/grid/performance_review/query/controller/PerformanceReviewController.java
- grid/src/main/java/org/highfives/grid/performance_review/query/dto/DetailPerformanceReviewDTO.java
- grid/src/main/java/org/highfives/grid/performance_review/query/dto/PerformanceReviewDTO.java
- grid/src/main/java/org/highfives/grid/performance_review/query/dto/ReviewItemDTO.java
- grid/src/main/java/org/highfives/grid/performance_review/query/repository/PerformanceReviewMapper.java
- grid/src/main/java/org/highfives/grid/performance_review/query/service/PerformanceReviewService.java
- grid/src/main/java/org/highfives/grid/performance_review/query/service/PerformanceReviewServiceImpl.java
- grid/src/main/java/org/highfives/grid/performance_review/query/vo/ResponseDetailReviewVO.java
- grid/src/main/java/org/highfives/grid/performance_review/query/vo/ResponsePerformanceReviewVO.java
- grid/src/main/resources/org/highfives/grid/performance_review/query/repository/PerformanceReviewMapper.xml
- grid/src/test/java/org/highfives/grid/performance_review/query/service/PerformanceReviewServiceImplTest.java
feature/performance-review -> develop
- 작성자 업적 평가 목록 조회
- 결재자 업적 평가 목록 조회
- 업적 평가 상세 조회
> Feat: 업적 평가 조회 기능 추가

- grid/src/main/java/org/highfives/grid/approval/command/aggregate/BTApproval.java
- grid/src/main/java/org/highfives/grid/approval/command/aggregate/OvertimeApproval.java
- grid/src/main/java/org/highfives/grid/approval/command/aggregate/RWApproval.java
- grid/src/main/java/org/highfives/grid/approval/command/aggregate/VacationApproval.java
- grid/src/main/java/org/highfives/grid/approval/command/controller/ApprovalController.java
- grid/src/main/java/org/highfives/grid/approval/command/repository/VApprovalRepository.java
- grid/src/main/java/org/highfives/grid/approval/command/service/ApprovalService.java
- grid/src/main/java/org/highfives/grid/approval/command/service/ApprovalServiceImpl.java
- grid/src/main/java/org/highfives/grid/approval/command/vo/ResApprovalVO.java
- grid/src/main/java/org/highfives/grid/approval/command/vo/VacationApprovalVO.java
- grid/src/main/java/org/highfives/grid/approval/common/dto/VacationApprovalDTO.java
- grid/src/main/java/org/highfives/grid/approval_chain/command/aggregate/VApprovalChain.java
- grid/src/main/java/org/highfives/grid/approval_chain/command/repository/VApprovalChainRepository.java
- grid/src/main/java/org/highfives/grid/approval_chain/command/service/ApprovalChainService.java
- grid/src/main/java/org/highfives/grid/approval_chain/command/service/ApprovalChainServiceImpl.java
- grid/src/main/java/org/highfives/grid/approval_chain/common/dto/VApprovalChainDTO.java
#109 #110 #111 #112 
모든 기능 정상 작동
> Feat: 휴가 결재 관련 기능 구현

- grid-f/grid-project/package-lock.json
- grid-f/grid-project/package.json
- grid-f/grid-project/src/App.vue
- grid-f/grid-project/src/main.js
- grid-f/grid-project/src/router/router.js
- grid-f/grid-project/src/views/Login.vue
- grid/src/main/java/org/highfives/grid/config/WebSecurityConfig.java
- grid/src/main/java/org/highfives/grid/security/GridLogoutFilter.java
- grid/src/main/java/org/highfives/grid/security/JwtFilter.java
- grid/src/main/java/org/highfives/grid/user/query/controller/UserController.java
- grid/src/main/java/org/highfives/grid/user/query/service/UserServiceImpl.java
feature/employee/login -> develop
팀장 / 부서장 정보 조회 시 id도 포함 되게 변경하였습니다.
> Fix: 팀장/부서장 정보 조회 반환값 변경 ( id포함 )

- grid/src/main/java/org/highfives/grid/performance_review/command/aggregate/PerformanceReviewStatus.java
- grid/src/main/java/org/highfives/grid/performance_review/command/aggregate/PerformanceReviewType.java
- grid/src/main/java/org/highfives/grid/performance_review/command/aggregate/entity/PerformanceReview.java
- grid/src/main/java/org/highfives/grid/performance_review/command/controller/PerformanceReviewController.java
- grid/src/main/java/org/highfives/grid/performance_review/command/dto/PerformanceReviewDTO.java
- grid/src/main/java/org/highfives/grid/performance_review/command/repository/PerformanceReviewRepository.java
- grid/src/main/java/org/highfives/grid/performance_review/command/service/PerformanceReviewService.java
- grid/src/main/java/org/highfives/grid/performance_review/command/service/PerformanceReviewServiceImpl.java
- grid/src/main/java/org/highfives/grid/performance_review/command/vo/ResponsePerformanceReviewVO.java
- grid/src/test/java/org/highfives/grid/performance_review/command/service/PerformanceReviewServiceImplTest.java
feature/performance-review -> develop
- 업적 평가 추가 기능
#126
> Feat: 업적 평가 추가 기능 구현

- grid/src/main/java/org/highfives/grid/approval/command/aggregate/BTApproval.java
- grid/src/main/java/org/highfives/grid/approval/command/aggregate/OvertimeApproval.java
- grid/src/main/java/org/highfives/grid/approval/common/dto/RWApprovalDTO.java
- grid/src/main/java/org/highfives/grid/approval_chain/command/aggregate/BTApprovalChain.java
- grid/src/main/java/org/highfives/grid/approval_chain/command/aggregate/OApprovalChain.java
- grid/src/main/java/org/highfives/grid/approval_chain/command/controller/ApprovalChainController.java
- grid/src/main/java/org/highfives/grid/approval_chain/command/service/ApprovalChainService.java
- grid/src/main/java/org/highfives/grid/approval_chain/command/service/ApprovalChainServiceImpl.java
- grid/src/main/java/org/highfives/grid/approval_chain/command/vo/ChainStatusVO.java
- grid/src/main/java/org/highfives/grid/approval_chain/common/dto/ChainDTO.java
- grid/src/main/java/org/highfives/grid/approval_chain/query/repository/ApprovalChainMapper.java
- grid/src/main/java/org/highfives/grid/approval_chain/query/service/ApprovalChainService.java
- grid/src/main/java/org/highfives/grid/approval_chain/query/service/ApprovalChainServiceImpl.java
- grid/src/main/resources/org/highfives/grid/approval_chain/query/repository/ApprovalChainMapper.xml
- grid/src/test/java/org/highfives/grid/approval_chain/command/service/ApprovalChainServiceImplTest.java
feature/approval-chain -> develop
#135 #136 #146 #150
모든 기능 정상 작동
> Feat: 출장 결재 승인/반려, 시간 외 근무 결재 승인/반려

- grid/src/main/java/org/highfives/grid/approval/command/aggregate/RWApproval.java
- grid/src/main/java/org/highfives/grid/approval_chain/command/aggregate/RWApprovalChain.java
- grid/src/main/java/org/highfives/grid/approval_chain/command/controller/ApprovalChainController.java
- grid/src/main/java/org/highfives/grid/approval_chain/command/repository/OApprovalChainRepository.java
- grid/src/main/java/org/highfives/grid/approval_chain/command/repository/RWApprovalChainRepository.java
- grid/src/main/java/org/highfives/grid/approval_chain/command/service/ApprovalChainService.java
- grid/src/main/java/org/highfives/grid/approval_chain/command/service/ApprovalChainServiceImpl.java
- grid/src/main/java/org/highfives/grid/approval_chain/query/repository/ApprovalChainMapper.java
- grid/src/main/java/org/highfives/grid/approval_chain/query/service/ApprovalChainService.java
- grid/src/main/java/org/highfives/grid/approval_chain/query/service/ApprovalChainServiceImpl.java
- grid/src/main/resources/org/highfives/grid/approval_chain/query/repository/ApprovalChainMapper.xml
feature/approval-chain -> develop
#148 #151
모든 기능 정상 작동
> Feat: 단축 근무 결재 승인/반려

- grid/src/main/java/org/highfives/grid/approval/command/aggregate/VacationApproval.java
- grid/src/main/java/org/highfives/grid/approval_chain/command/aggregate/VApprovalChain.java
- grid/src/main/java/org/highfives/grid/approval_chain/command/controller/ApprovalChainController.java
- grid/src/main/java/org/highfives/grid/approval_chain/command/repository/RWApprovalChainRepository.java
- grid/src/main/java/org/highfives/grid/approval_chain/command/repository/VApprovalChainRepository.java
- grid/src/main/java/org/highfives/grid/approval_chain/command/service/ApprovalChainService.java
- grid/src/main/java/org/highfives/grid/approval_chain/command/service/ApprovalChainServiceImpl.java
feature/approval-chain -> develop
#149 #152 
모든 기능 정상 작동
> Feat: 휴가 결재 승인/반려

- grid/src/main/java/org/highfives/grid/performance_review/command/aggregate/entity/ReviewGrade.java
- grid/src/main/java/org/highfives/grid/performance_review/command/aggregate/entity/TotalPerformanceReview.java
- grid/src/main/java/org/highfives/grid/performance_review/command/dto/ReviewGradeDTO.java
- grid/src/main/java/org/highfives/grid/performance_review/command/dto/TotalPerformanceReviewDTO.java
- grid/src/main/java/org/highfives/grid/performance_review/command/repository/PerformanceReviewItemRepository.java
- grid/src/main/java/org/highfives/grid/performance_review/command/repository/PerformanceReviewRepository.java
- grid/src/main/java/org/highfives/grid/performance_review/command/repository/ReviewGradeRepository.java
- grid/src/main/java/org/highfives/grid/performance_review/command/repository/TotalPerformanceReviewRepository.java
- grid/src/main/java/org/highfives/grid/performance_review/command/service/PerformanceReviewItemService.java
- grid/src/main/java/org/highfives/grid/performance_review/command/service/PerformanceReviewItemServiceImpl.java
- grid/src/main/java/org/highfives/grid/performance_review/command/service/PerformanceReviewServiceImpl.java
- grid/src/main/java/org/highfives/grid/performance_review/command/service/TotalPerformanceReviewService.java
- grid/src/main/java/org/highfives/grid/performance_review/command/service/TotalPerformanceReviewServiceImpl.java
- grid/src/test/java/org/highfives/grid/performance_review/command/service/PerformanceReviewItemServiceImplTest.java
- grid/src/test/java/org/highfives/grid/performance_review/command/service/PerformanceReviewServiceImplTest.java
- grid/src/test/java/org/highfives/grid/performance_review/command/service/TotalPerformanceReviewServiceImplTest.java
feature/performance-review -> develop
- 연말 업적 평가 확정시 종합 업적 평가 생성하는 기능 추가
> Feat: 종합 업적 평가 생성 기능

- grid-f/grid-project/package-lock.json
- grid-f/grid-project/package.json
- grid-f/grid-project/src/App.vue
- grid-f/grid-project/src/router/router.js
- grid/src/main/java/org/highfives/grid/approval/query/controller/ApprovalController.java
- grid/src/main/java/org/highfives/grid/approval/query/repository/ApprovalMapper.java
- grid/src/main/java/org/highfives/grid/approval/query/service/ApprovalService.java
- grid/src/main/java/org/highfives/grid/approval/query/service/ApprovalServiceImpl.java
- grid/src/main/resources/org/highfives/grid/approval/query/repository/ApprovalMapper.xml
- grid/src/main/resources/org/highfives/grid/approval_chain/query/repository/ApprovalChainMapper.xml
> Fix: 조회 관련 수정

- grid-f/grid-project/src/components/Vacation/Info/VacationInfo.vue
feature/vacation-front/sub
user로그인 하였을 때 자신의 휴가를 모아볼수있는것들 제작
> Feat: User로그인 하였을때 자신의 휴가를 모아볼수있는 화면 구현

- grid-f/grid-project/src/App.vue
- grid-f/grid-project/src/components/Approval/ApprovalChain.vue
- grid-f/grid-project/src/views/Approval/ApprovalDetailView.vue
- grid-f/grid-project/src/views/Approval/RegistBTApprovalView.vue
feature/approval-front -> develop
#242 #243 
모든 기능 정상 작동
> Feat: 직원별 승인/반려/취소 화면

- grid-f/grid-project/src/components/PerformanceReview/Goal/GoalAdd.vue
- grid-f/grid-project/src/components/PerformanceReview/Goal/GoalDetail.vue
- grid-f/grid-project/src/components/PerformanceReview/Goal/GoalList.vue
- grid-f/grid-project/src/components/PerformanceReview/Review/FinalPerformanceReviewAdd.vue
- grid-f/grid-project/src/components/PerformanceReview/Review/MidPerformanceReviewAdd.vue
- grid-f/grid-project/src/components/PerformanceReview/Review/PerformanceReivewList.vue
- grid-f/grid-project/src/components/PerformanceReview/Review/PerformanceReviewDetail.vue
- grid-f/grid-project/src/components/PerformanceReview/Total/TotalPerformanceReviewList.vue
- grid/src/main/java/org/highfives/grid/performance_review/query/controller/TotalPerformanceReviewController.java
- grid/src/main/java/org/highfives/grid/performance_review/query/dto/ReviewGradeDTO.java
- grid/src/main/java/org/highfives/grid/performance_review/query/dto/TotalPerformanceReviewDTO.java
- grid/src/main/java/org/highfives/grid/performance_review/query/repository/TotalPerformanceReviewMapper.java
- grid/src/main/java/org/highfives/grid/performance_review/query/service/TotalPerformanceReviewService.java
- grid/src/main/java/org/highfives/grid/performance_review/query/service/TotalPerformanceReviewServiceImpl.java
- grid/src/main/java/org/highfives/grid/performance_review/query/vo/ResponseDetailTotalVO.java
- grid/src/main/java/org/highfives/grid/performance_review/query/vo/ResponseTotalPerformanceReviewVO.java
- grid/src/main/resources/org/highfives/grid/performance_review/query/repository/TotalPerformanceReviewMapper.xml
fix/performance-review-front/review
업적 평가 유저 직원, 관리자 구분 직책 구분하는 기능 추가함
> Fix: 업적평가 유저 체크 하는 기능 추가

- grid-f/grid-project/src/components/Vacation/Info/VacationChangeInfo.vue
- grid-f/grid-project/src/components/Vacation/Info/VacationInfo.vue
- grid-f/grid-project/src/components/Vacation/Manage/VacationManage.vue
- grid-f/grid-project/src/components/Vacation/Policy/VacationPolicy.vue
feature/vacation-front/sub -> develop
모달, 카드, 표에 부트스트랩 적용
- 모달
- 카드
- 테이블, 페이지네이션
> Feat: bootstrap 디자인 추가

- grid-f/grid-project/src/App.vue
- grid-f/grid-project/src/components/AdTime/AdTimeAdd.vue
- grid-f/grid-project/src/components/AdTime/WorkCalendar.vue
- grid-f/grid-project/src/components/Header.vue
- grid-f/grid-project/src/components/PerformanceReview/Goal/GoalAdd.vue
- grid-f/grid-project/src/components/PerformanceReview/Goal/GoalDetail.vue
- grid-f/grid-project/src/components/PerformanceReview/Goal/GoalList.vue
- grid-f/grid-project/src/components/PerformanceReview/Review/FinalPerformanceReviewAdd.vue
- grid-f/grid-project/src/components/PerformanceReview/Review/MidPerformanceReviewAdd.vue
- grid-f/grid-project/src/components/PerformanceReview/Review/PerformanceReviewDetail.vue
- grid-f/grid-project/src/components/Sidebar.vue
- grid-f/grid-project/src/router/router.js
- grid/src/main/java/org/highfives/grid/performance_review/command/controller/PerformanceReviewGoalController.java
- grid/src/main/java/org/highfives/grid/performance_review/command/service/PerformanceReviewGoalItemServiceImpl.java
- grid/src/main/java/org/highfives/grid/performance_review/command/service/PerformanceReviewGoalServiceImpl.java
fix/pr-ad-f -> develop
- 목표 작성 3월에 가능, 팀원만 작성
- 중간 평가 팀원만 작성(중간 평가 작성 6월에 가능한건 주석)
- 연말 평가 팀원만 작성(연말 평가 작성 12월에 가능한건 주석)
-  항목 삭제시 alret 추가
-  제출저장시 alret추가
- 가중치 숫자만 입력 가능
- 평가 등급 id 말고 알파벳으로 조회
> Fix: 업적평가, 출퇴근 수정

- grid-f/grid-project/src/components/Vacation/Info/VacationChangeInfo.vue
- grid-f/grid-project/src/components/Vacation/Info/VacationInfo.vue
- grid-f/grid-project/src/components/Vacation/Manage/VacationManage.vue
- grid-f/grid-project/src/components/Vacation/Policy/VacationPolicy.vue
feature/vacation-front/sub -> develop
부트스트랩 적용 및 검증기능을 추가
> Feat: 부트스트랩 및 검증기능 추가

- grid-f/grid-project/src/views/Approval/RegistBTApprovalView.vue
- grid-f/grid-project/src/views/Approval/RegistOApprovalView.vue
- grid-f/grid-project/src/views/Approval/RegistRWApprovalView.vue
- grid-f/grid-project/src/views/Approval/RegistVApprovalView.vue
fix/approval -> develop
작성자 아이디 토큰으로 구분
결재 작성 기능 정상 작동
> Fix: 결재 생성 기능 관련 수정

- grid-f/grid-project/src/components/PerformanceReview/Goal/GoalAdd.vue
- grid-f/grid-project/src/components/PerformanceReview/Goal/GoalDetail.vue
- grid-f/grid-project/src/components/PerformanceReview/Goal/GoalList.vue
- grid-f/grid-project/src/components/PerformanceReview/Review/FinalPerformanceReviewAdd.vue
- grid-f/grid-project/src/components/PerformanceReview/Review/MidPerformanceReviewAdd.vue
- grid-f/grid-project/src/components/PerformanceReview/Review/PerformanceReivewList.vue
- grid-f/grid-project/src/components/PerformanceReview/Review/PerformanceReviewDetail.vue
- grid-f/grid-project/src/components/PerformanceReview/Total/TotalPerformanceReivewDetail.vue
- grid-f/grid-project/src/components/PerformanceReview/Total/TotalPerformanceReviewList.vue
- grid-f/grid-project/src/views/PerformanceReview/Goal/GoalAddView.vue
- grid-f/grid-project/src/views/PerformanceReview/Goal/GoalDetailView.vue
- grid-f/grid-project/src/views/PerformanceReview/Goal/GoalListView.vue
- grid-f/grid-project/src/views/PerformanceReview/Review/FinalPerformanceReviewAddView.vue
- grid-f/grid-project/src/views/PerformanceReview/Review/MidPerformanceReviewAddView.vue
- grid-f/grid-project/src/views/PerformanceReview/Review/PerformanceReviewDetailView.vue
- grid-f/grid-project/src/views/PerformanceReview/Review/PerformanceReviewListView.vue
- grid-f/grid-project/src/views/PerformanceReview/Total/TotalPerformanceReviewDetailView.vue
- grid-f/grid-project/src/views/PerformanceReview/Total/TotalPerformanceReviewListView.vue
Fix/pr-ad-front -> develop
업적 평가 css 수정했습니다
- 페이지네이션은 수정 필요
테스트 성공
> Fix: 업적 평가 css 수정

- grid-f/grid-project/src/components/Sidebar.vue
- grid-f/grid-project/src/components/Vacation/Info/VacationChangeInfo.vue
- grid-f/grid-project/src/components/Vacation/Info/VacationInfo.vue
- grid-f/grid-project/src/components/Vacation/Manage/VacationManage.vue
- grid-f/grid-project/src/components/Vacation/Policy/VacationPolicy.vue
- grid/src/main/java/org/highfives/grid/vacation/command/entity/VacationType.java
- grid/src/main/java/org/highfives/grid/vacation/command/service/VacationServiceImpl.java
- grid/src/main/java/org/highfives/grid/vacation/command/vo/ModifyVacationType.java
- grid/src/main/java/org/highfives/grid/vacation/command/vo/RegistVacationType.java
- grid/src/main/java/org/highfives/grid/vacation/query/controller/VacationController.java
- grid/src/main/java/org/highfives/grid/vacation/query/dto/VacationTypeDTO.java
- grid/src/main/java/org/highfives/grid/vacation/query/entity/VacationType.java
- grid/src/main/java/org/highfives/grid/vacation/query/repository/VacationMapper.java
- grid/src/main/java/org/highfives/grid/vacation/query/service/VacationService.java
- grid/src/main/java/org/highfives/grid/vacation/query/service/VacationServiceImpl.java
- grid/src/main/resources/org/highfives/grid/vacation/query/repository/VacationMapper.xml
feature/vacation-front/semi
- 사이드바에서 휴가종류를 관리자용 화면으로 분류
- 정책 똑같은거 등록 못하도록 예외처리 추가
- 휴가 정책이 있으면 휴가종류 삭제못하도록 예외처리 추가
- 휴가 직접지급시에 사번의 직원이 존재하지않으면 예외처리 추가
- 지급된 휴가가 있으면 휴가종류 삭제안되도록 예외처리 추가
- 휴가 종류를 삭제하는대신 비활성화/활성화 하도록 기능 추가
> Feat: 멘토님 피드백 수정 및 기능 추가

- grid-f/grid-project/src/components/Vacation/Info/VacationChangeInfo.vue
- grid-f/grid-project/src/components/Vacation/Info/VacationInfo.vue
- grid-f/grid-project/src/components/Vacation/Manage/VacationManage.vue
- grid-f/grid-project/src/components/Vacation/Policy/VacationPolicy.vue
- grid/src/main/resources/org/highfives/grid/vacation/query/repository/VacationMapper.xml
feature/css-fix -> develop
css 수정
> Fix: css 수정 및 조건문 수정

- grid-f/grid-project/package-lock.json
- grid-f/grid-project/src/components/Department/Department.vue
- grid-f/grid-project/src/components/Department/Team.vue
- grid-f/grid-project/src/components/Header.vue
- grid-f/grid-project/src/components/Sidebar.vue
- grid-f/grid-project/src/components/TeamReview/AddTeamReview.vue
- grid-f/grid-project/src/components/TeamReview/MyReview.vue
- grid-f/grid-project/src/components/TeamReview/ReviewHistory.vue
- grid-f/grid-project/src/components/TeamReview/ReviewList.vue
- grid/build.gradle
- grid/src/main/java/org/highfives/grid/department/command/controller/DepartmentController.java
- grid/src/main/java/org/highfives/grid/department/command/service/DepartmentService.java
- grid/src/main/java/org/highfives/grid/department/command/service/DepartmentServiceImpl.java
- grid/src/main/resources/application.yaml
- grid/src/main/resources/org/highfives/grid/department/query/repository/DepartmentMapper.xml
- grid/src/main/resources/org/highfives/grid/department/query/repository/TeamMapper.xml
- grid/src/main/resources/org/highfives/grid/review/query/repository/ReviewMapper.xml
fix/review -> develop
권한에 따른 기능 분류 및 Header.vue 에서 부서리스트 모달 프로필 이동시 검은 화면 유지 현상 수정 및 닫기 버튼 외의 방법으로 닫을 시 검은 화면 유지 현상 수정
closed #300 #302 #301
> fix : 버그 수정 및 권한에 따른 기능 분류

- grid-f/grid-project/src/views/Approval/MyApprovalListView.vue
- grid-f/grid-project/src/views/Approval/RequiredApprovalListView.vue
feature/css-fix -> develop
css 수정
> Fix: css 수정

- grid-f/grid-project/src/components/Department/Department.vue
- grid-f/grid-project/src/components/Department/Team.vue
- grid-f/grid-project/src/components/TeamReview/AddTeamReview.vue
- grid-f/grid-project/src/components/TeamReview/MyReview.vue
- grid-f/grid-project/src/components/TeamReview/ReviewHistory.vue
- grid-f/grid-project/src/components/TeamReview/ReviewList.vue
- grid/build.gradle
- grid/src/main/java/org/highfives/grid/department/command/controller/DepartmentController.java
- grid/src/main/java/org/highfives/grid/department/command/controller/TeamController.java
- grid/src/main/java/org/highfives/grid/department/command/service/DepartmentService.java
- grid/src/main/java/org/highfives/grid/department/command/service/DepartmentServiceImpl.java
- grid/src/main/java/org/highfives/grid/department/command/service/TeamService.java
- grid/src/main/java/org/highfives/grid/department/command/service/TeamServiceImpl.java
fix/department -> develop
부서장, 팀장 변경 수정 및 alert 수정
> Fix : 부서장, 팀장 변경 수정 및 alert 수정

- grid-f/grid-project/src/components/Vacation/Info/VacationChangeInfo.vue
- grid-f/grid-project/src/components/Vacation/Manage/VacationManage.vue
feature/css-fix -> develop
휴가종류를 등록할 때 이름이 중복되면 등록이 안되도록 검증 추가
> Feat: 중복되는 휴가이름 검증 추가

- grid-f/grid-project/src/components/AdTime/AdTimeAdd.vue
- grid-f/grid-project/src/components/AdTime/AdTimeList.vue
- grid-f/grid-project/src/components/PerformanceReview/Goal/GoalAdd.vue
- grid-f/grid-project/src/components/PerformanceReview/Goal/GoalDetail.vue
- grid-f/grid-project/src/components/PerformanceReview/Goal/GoalList.vue
- grid-f/grid-project/src/components/PerformanceReview/Review/FinalPerformanceReviewAdd.vue
- grid-f/grid-project/src/components/PerformanceReview/Review/MidPerformanceReviewAdd.vue
- grid-f/grid-project/src/components/PerformanceReview/Review/PerformanceReivewList.vue
- grid-f/grid-project/src/components/PerformanceReview/Review/PerformanceReviewDetail.vue
- grid-f/grid-project/src/components/PerformanceReview/Total/TotalPerformanceReivewDetail.vue
- grid-f/grid-project/src/components/PerformanceReview/Total/TotalPerformanceReviewList.vue
- grid/src/main/java/org/highfives/grid/performance_review/command/service/PerformanceReviewServiceImpl.java
- grid/src/main/java/org/highfives/grid/performance_review/query/dto/ReviewGradeDTO.java
- grid/src/main/java/org/highfives/grid/performance_review/query/dto/ReviewItemDTO.java
- grid/src/main/resources/org/highfives/grid/performance_review/query/repository/PerformanceReviewGoalMapper.xml
- grid/src/main/resources/org/highfives/grid/performance_review/query/repository/PerformanceReviewMapper.xml
- grid/src/main/resources/org/highfives/grid/performance_review/query/repository/TotalPerformanceReviewMapper.xml
fix/pr-ad-fix -> develop
회원 출퇴근시 출근 완료 퇴근 완료  alert창 추가
상신할 때 반려의견 다 지우기
점수 더블로 조회
중간 점수, 연말 점수 총 몇점인지
확인 없애기 -> 버튼만 지움
안되는 건 비활성화
종합평가 점수 소수점 둘째자리에서 반올림해서 보여줌
테스트 성공
> Fix: 멘토님 피드백, 오류 수정

- grid-f/grid-project/src/components/Department/Department.vue
- grid-f/grid-project/src/components/Department/Team.vue
- grid-f/grid-project/src/components/Department/TeamMemberList.vue
- grid-f/grid-project/src/components/Header.vue
- grid-f/grid-project/src/components/Sidebar.vue
- grid-f/grid-project/src/components/TeamReview/MyReview.vue
- grid-f/grid-project/src/components/TeamReview/ReviewHistory.vue
- grid/src/main/java/org/highfives/grid/department/command/controller/TeamController.java
- grid/src/main/java/org/highfives/grid/department/command/service/DepartmentServiceImpl.java
- grid/src/main/java/org/highfives/grid/department/command/service/TeamService.java
- grid/src/main/java/org/highfives/grid/department/command/service/TeamServiceImpl.java
- grid/src/main/java/org/highfives/grid/user/command/controller/UserController.java
- grid/src/main/resources/org/highfives/grid/review/query/repository/ReviewMapper.xml
fix/pr-ad-fix -> develop
작성이 완료된 평가만 확인할 수 있도록 수정, 팀 활성/비활성 버튼 생성
> Fix : 멘토링 피드백 및 부트스트랩 추가

- grid-f/grid-project/src/components/Department/Department.vue
- grid-f/grid-project/src/components/Department/Team.vue
- grid-f/grid-project/src/components/TeamReview/ReviewHistory.vue
- grid/src/main/java/org/highfives/grid/department/command/repository/DepartmentRepository.java
- grid/src/main/java/org/highfives/grid/department/command/repository/TeamRepository.java
- grid/src/main/java/org/highfives/grid/department/command/service/DepartmentServiceImpl.java
- grid/src/main/java/org/highfives/grid/department/command/service/TeamServiceImpl.java
- grid/src/main/java/org/highfives/grid/review/command/service/ReviewServiceImpl.java
- grid/src/main/java/org/highfives/grid/user/command/aggregate/Employee.java
- grid/src/main/java/org/highfives/grid/user/command/repository/UserRepository.java
fix/department-bug -> develop
(부서,팀)추가/(부서장,팀장)수정 시 직책 안바뀌는 현상 수정, 부서코드,부서명 겹칠시 alert 표시, 동료 평가 생성 시 일정년도 이하 일 시 alert 표시
> Fix : 예외처리, 작동 안될시 alert 표시

- grid-f/grid-project/src/components/Header.vue
- grid/src/main/java/org/highfives/grid/security/GridLogoutFilter.java
- grid/src/main/java/org/highfives/grid/security/JwtUtil.java
> Fix : Proxy 적용

- grid/src/main/java/org/highfives/grid/security/AuthenticationFilter.java
- grid/src/main/java/org/highfives/grid/security/JwtUtil.java
- grid/src/main/java/org/highfives/grid/user/command/service/TokenReissueServiceImpl.java
> FIX : samesite 등록

- grid/src/main/java/org/highfives/grid/approval/query/service/PdfServiceImpl.java
- grid/src/main/resources/org/highfives/grid/approval/query/repository/ApprovalMapper.xml
fix/approval -> develop
목록에서 최신 결재가 위에 오도록 내림차순 정렬
> Feat: 목록 내림차순 정렬

- grid-f/grid-project/src/components/AdTime/AdTimeList.vue
- grid-f/grid-project/src/components/PerformanceReview/Goal/GoalAdd.vue
- grid-f/grid-project/src/components/PerformanceReview/Goal/GoalList.vue
- grid-f/grid-project/src/components/PerformanceReview/Review/FinalPerformanceReviewAdd.vue
- grid-f/grid-project/src/components/PerformanceReview/Review/MidPerformanceReviewAdd.vue
- grid-f/grid-project/src/components/PerformanceReview/Review/PerformanceReivewList.vue
- grid/src/main/java/org/highfives/grid/GridApplication.java
- grid/src/main/java/org/highfives/grid/work/command/service/AdSchedulerService.java
Fix/pr ad fix fb -> develop
-문서 상태 css 추가
- 23시 59분 59초까지 퇴근을 찍지 않은 경우 자동 퇴근처리
- 업적평가 기간 성정(시연을 위해 주석 처리)
옳은 값 입력시 테스트 통과
> Fix: 퇴근 자동 설정, 업적 평가 기간 추가,css 배지 추가

- README.md
- grid-f/grid-project/.ebextensions/00-set-timezone.config
- grid-f/grid-project/Dockerfile
- grid-f/grid-project/src/components/Approval/ApprovalChain.vue
- grid-f/grid-project/src/views/Approval/ApprovalDetailView.vue
- grid-f/grid-project/src/views/Approval/BTApprovalListView.vue
- grid-f/grid-project/src/views/Approval/MyApprovalListView.vue
- grid-f/grid-project/src/views/Approval/OApprovalListView.vue
- grid-f/grid-project/src/views/Approval/RWApprovalListView.vue
- grid-f/grid-project/src/views/Approval/RegistBTApprovalView.vue
- grid-f/grid-project/src/views/Approval/RegistOApprovalView.vue
- grid-f/grid-project/src/views/Approval/RegistRWApprovalView.vue
- grid-f/grid-project/src/views/Approval/RegistVApprovalView.vue
- grid-f/grid-project/src/views/Approval/RequiredApprovalListView.vue
- grid-f/grid-project/src/views/HumanResources/Main.vue
- grid/.ebextensions/00-set-timezone.config
- grid/Dockerfile
- grid/src/main/java/org/highfives/grid/approval/query/service/PdfServiceImpl.java
- grid/src/main/java/org/highfives/grid/user/query/vo/SimpleInfo.java
> Fix: 경로 수정, 시간 입력 오류 수정, 인감 이미지 수정

- grid/src/main/java/org/highfives/grid/approval/query/service/PdfServiceImpl.java
fix/approval -> develop
오류 체크 위한 출력 코드 추가
> Fix: 오류 체크 코드 추가

- grid/src/main/java/org/highfives/grid/approval/query/service/PdfServiceImpl.java
> Fix: 오류 수정 위한 출력 코드 추가

- grid/src/main/java/org/highfives/grid/approval/query/service/PdfServiceImpl.java
> Fix: 오류 수정 위한 코드 추가

- grid-f/grid-project/index.html
- grid-f/grid-project/src/components/Sidebar.vue
- grid-f/grid-project/src/views/HumanResources/Main.vue
> FIX: 사이드바 수정

- grid-f/grid-project/src/components/HumanResources/HumanResourcesInfo.vue
- grid-f/grid-project/src/views/HumanResources/Profile.vue
> FIX : 단일 유저 프로필 화면 여백 조절

- grid-f/grid-project/src/components/Vacation/Manage/VacationManage.vue
feature/vacationFinal -> develop
기존에 수정하기 모달에서 있던 활성/비활성을 따로 버튼을 빼서 만들고 비활성 상태일때에는 해당 타입이 출력이 안되도록 변경
> Feat: 활성/비활성 버튼 추가 및 모달추가

- grid-f/grid-project/src/components/Vacation/Info/VacationChangeInfo.vue
- grid-f/grid-project/src/components/Vacation/Manage/VacationManage.vue
- grid-f/grid-project/src/components/Vacation/Policy/VacationPolicy.vue
- grid/src/main/resources/org/highfives/grid/vacation/query/repository/VacationMapper.xml
feature/vacationFinal
가이드 모달을 추가하였습니다.
> Feat: 가이드 모달 추가

- grid/src/main/java/org/highfives/grid/approval/query/controller/ApprovalController.java
- grid/src/main/java/org/highfives/grid/approval/query/service/ApprovalService.java
- grid/src/main/java/org/highfives/grid/approval/query/service/ApprovalServiceImpl.java
- grid/src/main/resources/org/highfives/grid/approval/query/repository/ApprovalMapper.xml
> Fix: 특정 일자 출장 인원 조회

- grid-f/grid-project/src/components/Spinner.vue
- grid-f/grid-project/src/views/Login/FindPwd.vue
- grid/src/main/java/org/highfives/grid/user/command/aggregate/Employee.java
- grid/src/main/java/org/highfives/grid/user/command/service/UserServiceImpl.java
> FIX :비밀번호 찾기 화면 스피너 추가 / 퇴사시 로직 추가 ( 부재중 상태 와 상태 메세지 업로드 )

- grid-f/grid-project/src/components/AdTime/AdTimeAdd.vue
- grid-f/grid-project/src/components/AdTime/AdTimeList.vue
- grid-f/grid-project/src/components/AdTime/AllWorkCalendar.vue
- grid-f/grid-project/src/views/AdTime/WorkCalendarView.vue
- grid-f/grid-project/src/views/Main/Main.vue
- 관리자 메인화면 수정
- 직원별 근태 조회 추가
fix/calendar -> develop
- 풀캘린더 css 수정 추가
- 관리자 메인화면 변경
잘 조회되어 보여짐
> Fix: 풀캘린더 추가, css 수정

- grid-f/grid-project/src/components/Vacation/Info/VacationChangeInfo.vue
- grid-f/grid-project/src/components/Vacation/Manage/VacationManage.vue
- grid-f/grid-project/src/components/Vacation/Policy/VacationPolicy.vue
> Fix: 휴가 타이틀 버튼 수정

- grid-f/grid-project/src/components/HumanResources/HumanResourcesInfo.vue
- grid-f/grid-project/src/components/HumanResources/ModifyInfo.vue
- grid-f/grid-project/src/views/HumanResources/Main.vue
- grid-f/grid-project/src/views/HumanResources/Profile.vue
- grid/src/main/java/org/highfives/grid/config/WebMvcConfig.java
- grid/src/main/java/org/highfives/grid/security/JwtInterceptor.java
- grid/src/main/java/org/highfives/grid/user/command/controller/UserController.java
- grid/src/main/java/org/highfives/grid/user/command/service/UserService.java
- grid/src/main/java/org/highfives/grid/user/command/service/UserServiceImpl.java
- grid/src/main/java/org/highfives/grid/user/command/vo/ReqResignStatusVO.java
- grid/src/main/java/org/highfives/grid/user/query/controller/UserController.java
- grid/src/main/java/org/highfives/grid/user/query/repository/UserMapper.java
- grid/src/main/java/org/highfives/grid/user/query/service/UserService.java
- grid/src/main/java/org/highfives/grid/user/query/service/UserServiceImpl.java
- grid/src/main/resources/org/highfives/grid/user/query/repository/UserMapper.xml
> Feature : 퇴사자 재입사 기능 추가

- grid-f/grid-project/src/views/Approval/RegistVApprovalView.vue
feature/vacationFinal -> develop
휴가결재 올릴때 휴가의 사용기한이 신청하는날짜보다 빠르면 결재를 올릴수 없도록 검증기능 추가
> Feat: 휴가 사용기한 날짜 검증기능 추가

- grid-f/grid-project/src/components/PerformanceReview/Goal/GoalAdd.vue
- grid-f/grid-project/src/components/PerformanceReview/Goal/GoalDetail.vue
- grid-f/grid-project/src/components/PerformanceReview/Goal/GoalList.vue
- grid-f/grid-project/src/components/PerformanceReview/Review/FinalPerformanceReviewAdd.vue
- grid-f/grid-project/src/components/PerformanceReview/Review/MidPerformanceReviewAdd.vue
- grid-f/grid-project/src/components/PerformanceReview/Review/PerformanceReivewList.vue
- grid-f/grid-project/src/components/PerformanceReview/Review/PerformanceReviewDetail.vue
- grid-f/grid-project/src/components/PerformanceReview/Total/TotalPerformanceReivewDetail.vue
- grid-f/grid-project/src/components/PerformanceReview/Total/TotalPerformanceReviewList.vue
- grid/src/main/java/org/highfives/grid/performance_review/query/dto/ApproverDTO.java
fix/pr-approval
- approver employeeNumber 추가
- 타이틀 css 수정
> Fix: approver, css

- grid/src/main/java/org/highfives/grid/approval/query/service/PdfServiceImpl.java
> Fix: 폰트 경로 수정

- grid-f/grid-project/index.html
> FIX: favicon

- grid/src/main/java/org/highfives/grid/review/command/service/ReviewServiceImpl.java
ex) test/prometheus -> develop
> Refactor: addReviewHistory 메소드 코드 리팩토링 및 프로메테우스 테스트 

- grid-f/grid-project/src/components/Vacation/Info/VacationChangeInfo.vue
- grid-f/grid-project/src/components/Vacation/Manage/VacationManage.vue
- grid-f/grid-project/src/views/Approval/RegistVApprovalView.vue
- grid/src/main/java/org/highfives/grid/vacation/command/entity/VacationType.java
- grid/src/main/java/org/highfives/grid/vacation/command/service/VacationServiceImpl.java
- grid/src/main/java/org/highfives/grid/vacation/command/vo/ModifyVacationType.java
- grid/src/main/java/org/highfives/grid/vacation/command/vo/RegistVacationType.java
- grid/src/main/java/org/highfives/grid/vacation/query/dto/VacationTypeDTO.java
- grid/src/main/resources/org/highfives/grid/vacation/query/repository/VacationMapper.xml
feature/cssFin -> develop
휴가 종류추가할때 시간으로 체크할 수 있는것을 넣어서 시간값 체크를 통해 
결재에도 유동적으로  적용가능하게 기능 추가
> Feat: 휴가 종류별 시간체크 기능 추가

- grid-f/grid-project/src/components/TeamReview/MyReview.vue
- grid-f/grid-project/src/components/TeamReview/ReviewList.vue
- grid/.gitignore
> Fix: 화면 타이틀 수정

- grid/src/main/java/org/highfives/grid/approval_chain/command/service/ApprovalChainServiceImpl.java
feature/cssFin -> develop
휴가 신청했을때 날짜가 계산이 잘못되는 오류 수정
> Fix: 날짜계산 오류 수정

- grid-f/grid-project/src/App.vue
- grid-f/grid-project/src/components/Header.vue
- grid-f/grid-project/src/components/Sidebar.vue
- grid-f/grid-project/src/views/HumanResources/Profile.vue
- grid/src/main/java/org/highfives/grid/security/GridLogoutFilter.java
fix/t4e1-5 -> develop 
토큰 시간 연장 시 화면 유지되게 변경 
화면 이동 시 토큰 시간 초기화 
사이드바 특정 메뉴에 대해 유저 직책이 4일 경우만 보이게함
헤더 드롭다운 메뉴 hover 로 변경
본인 이외의 유저 관리 정보가 보이는 문제 해결
로그아웃 시 refresh 쿠키 안지우는 문제 해결
로컬 환경에서 테스트 완료
> Fix : 기능 추가 및 문제 해결 

- grid-f/grid-project/src/components/Vacation/Info/VacationChangeInfo.vue
- grid-f/grid-project/src/components/Vacation/Info/VacationInfo.vue
- grid/src/main/java/org/highfives/grid/vacation/command/entity/VacationHistory.java
- grid/src/main/java/org/highfives/grid/vacation/command/service/VacationServiceImpl.java
- grid/src/main/java/org/highfives/grid/vacation/query/dto/VacationHistoryDTO.java
- grid/src/main/java/org/highfives/grid/vacation/query/entity/VacationHistory.java
- grid/src/main/resources/org/highfives/grid/vacation/query/repository/VacationMapper.xml
feature/cssFin -> develop
- 기존 휴가 보유정보에서 테이블 컬럼명 수정 및 삭제
- 휴가변화이력에 새로운 컬럼 추가 및 데이터 가져오기위한 백엔드 코드 수정
> Feat: 테이블 컬럼 추가/삭제 및 변경개수 가져오는 기능 추가

- grid-f/grid-project/src/components/Department/Department.vue
- grid-f/grid-project/src/components/Department/Team.vue
- grid-f/grid-project/src/components/Department/TeamMemberList.vue
- grid-f/grid-project/src/components/Header.vue
- grid-f/grid-project/src/components/TeamReview/AddTeamReview.vue
- grid-f/grid-project/src/components/TeamReview/ReviewHistory.vue
- grid-f/grid-project/src/components/TeamReview/ReviewList.vue
- grid/build.gradle
- grid/build/resources/main/application.yaml
- grid/build/resources/main/org/highfives/grid/review/query/repository/ReviewMapper.xml
- grid/build/resources/main/org/highfives/grid/vacation/query/repository/VacationMapper.xml
- grid/src/main/java/org/highfives/grid/review/query/aggregate/ReviewEmployeeHistory.java
- grid/src/main/java/org/highfives/grid/review/query/controller/ReviewController.java
- grid/src/main/java/org/highfives/grid/review/query/dto/ReviewEmployeesHistoryDTO.java
- grid/src/main/java/org/highfives/grid/review/query/repository/ReviewMapper.java
- grid/src/main/java/org/highfives/grid/review/query/service/ReviewService.java
- grid/src/main/java/org/highfives/grid/review/query/service/ReviewServiceImpl.java
- grid/src/main/resources/org/highfives/grid/review/query/repository/ReviewMapper.xml
ex) fix/review-v1 -> develop
멘토링 피드백 수정, 모달 버튼 중앙으로 정렬, 페이징처리 백엔드에서 구현
> Fix: 멘토링 피드백

- grid-f/grid-project/src/views/Approval/RegistBTApprovalView.vue
- grid-f/grid-project/src/views/Approval/RegistRWApprovalView.vue
- grid-f/grid-project/src/views/Approval/RegistVApprovalView.vue
> Fix: 제출 버튼 위치 조정

- grid-f/grid-project/src/components/AdTime/AllWorkCalendar.vue
- grid-f/grid-project/src/components/AdTime/WorkCalendar.vue
- grid/src/main/resources/org/highfives/grid/approval/query/repository/ApprovalMapper.xml
- 겹쳐지는 오류 수정
- 시간 설정 수정
- popover 내용 수정
fix/calender -> develop
- css 수정
> Fix: 캘린더  more, popover 수정

- grid-f/grid-project/src/components/Header.vue
- grid-f/grid-project/src/router/router.js
- grid-f/grid-project/src/views/HumanResources/Main.vue
- grid/build/resources/main/org/highfives/grid/vacation/query/repository/VacationMapper.xml
- grid/src/main/java/org/highfives/grid/security/GridLogoutFilter.java
- grid/src/main/java/org/highfives/grid/security/JwtUtil.java
- grid/src/main/java/org/highfives/grid/user/command/dto/UserDTO.java
- grid/src/main/java/org/highfives/grid/user/command/service/UserServiceImpl.java
- grid/src/main/java/org/highfives/grid/user/exception/InvalidNumberException.java
- grid/src/main/java/org/highfives/grid/user/exception/UserNotFoundException.java
- grid/src/main/java/org/highfives/grid/user/query/controller/UserController.java
- grid/src/main/java/org/highfives/grid/user/query/dto/DepartmentDTO.java
- grid/src/main/java/org/highfives/grid/user/query/dto/DutiesDTO.java
- grid/src/main/java/org/highfives/grid/user/query/dto/PositionDTO.java
- grid/src/main/java/org/highfives/grid/user/query/dto/TeamDTO.java
- grid/src/main/java/org/highfives/grid/user/query/dto/UserDTO.java
- grid/src/main/java/org/highfives/grid/user/query/service/UserService.java
- grid/src/main/java/org/highfives/grid/user/query/service/UserServiceImpl.java
- grid/src/test/java/org/highfives/grid/user/command/service/UserServiceImplTests.java
- grid/src/test/java/org/highfives/grid/user/query/service/UserServiceImplTests.java
> FIX : 비밀번호 찾기 라우팅 수정

- grid-f/grid-project/src/views/HumanResources/Main.vue
> FIX : csv다운로드 부서/ 팀명이 나오도록

- grid-f/grid-project/src/components/AdTime/AdTimeList.vue
- grid-f/grid-project/src/components/AdTime/AllWorkCalendar.vue
- grid-f/grid-project/src/components/PerformanceReview/Goal/GoalAdd.vue
- grid-f/grid-project/src/components/PerformanceReview/Goal/GoalDetail.vue
- grid-f/grid-project/src/components/PerformanceReview/Goal/GoalList.vue
- grid-f/grid-project/src/components/PerformanceReview/Review/FinalPerformanceReviewAdd.vue
- grid-f/grid-project/src/components/PerformanceReview/Review/MidPerformanceReviewAdd.vue
- grid-f/grid-project/src/components/PerformanceReview/Review/PerformanceReivewList.vue
- grid-f/grid-project/src/components/PerformanceReview/Review/PerformanceReviewDetail.vue
- grid-f/grid-project/src/components/PerformanceReview/Total/TotalPerformanceReivewDetail.vue
- grid-f/grid-project/src/components/PerformanceReview/Total/TotalPerformanceReviewList.vue
- 캘린더 크기 수정
- 가이드 커서 추가
fix/pr-ad-testcase -> develop
css 수정
> Fix: 캘린더, 가이드 css 수정

- grid-f/grid-project/src/components/PerformanceReview/Total/TotalPerformanceReivewDetail.vue
> Fix: 종합평가 상세 수정

- grid/src/test/java/org/highfives/grid/performance_review/command/service/PerformanceReviewGoalItemServiceImplTest.java
- grid/src/test/java/org/highfives/grid/performance_review/command/service/PerformanceReviewGoalServiceImplTest.java
- grid/src/test/java/org/highfives/grid/performance_review/command/service/PerformanceReviewServiceImplTest.java
- grid/src/test/java/org/highfives/grid/performance_review/command/service/TotalPerformanceReviewServiceImplTest.java
- grid/src/test/java/org/highfives/grid/performance_review/query/service/PerformanceReviewGoalServiceImplTest.java
- grid/src/test/java/org/highfives/grid/performance_review/query/service/PerformanceReviewServiceImplTest.java
- grid/src/test/java/org/highfives/grid/performance_review/query/service/TotalPerformanceReviewServiceImplTest.java
- grid/src/test/java/org/highfives/grid/work/command/service/AdTimeServiceImplTest.java
- grid/src/test/java/org/highfives/grid/work/query/service/AdTimeServiceImplTest.java
> Fix: 출퇴근, 업적 평가 테스트코드 추가

- grid/build/resources/main/application.yaml
- grid/src/test/java/org/highfives/grid/department/command/service/DepartmentServiceImplTest.java
- grid/src/test/java/org/highfives/grid/department/command/service/TeamServiceImplTest.java
- grid/src/test/java/org/highfives/grid/department/query/service/DepartmentServiceImplTest.java
- grid/src/test/java/org/highfives/grid/department/query/service/TeamServiceImplTest.java
- grid/src/test/java/org/highfives/grid/review/command/service/ReviewServiceImplTest.java
- grid/src/test/java/org/highfives/grid/review/query/service/ReviewServiceImplTest.java
> Fix : TDD 수정

- grid-f/grid-project/src/components/Vacation/Info/VacationChangeInfo.vue
- grid-f/grid-project/src/components/Vacation/Info/VacationInfo.vue
- grid-f/grid-project/src/components/Vacation/Manage/VacationManage.vue
- grid-f/grid-project/src/components/Vacation/Policy/VacationPolicy.vue
- grid-f/grid-project/src/views/HumanResources/AddMulti.vue
- grid-f/grid-project/src/views/HumanResources/Modify.vue
- grid-f/grid-project/src/views/HumanResources/ModifyMulti.vue
- grid/src/main/java/org/highfives/grid/user/command/service/TokenReissueServiceImpl.java
- grid/src/test/java/org/highfives/grid/user/command/service/TokenReissueServiceImplTest.java
fix/t4e1-6 -> main 
인사 정보 변경, 사원 추가, 사원 정보 일괄 수정 화면 icon 변경
휴가 관련 화면 타이틀 변경 ( grid 컬럼 조정 )
테스트 전부 통과
> FIX : 토큰 관련 서비스 코드 추가, 프론트 css 변경

- grid-f/grid-project/src/components/Header.vue
- grid/src/main/java/org/highfives/grid/security/GridLogoutFilter.java
- grid/src/main/java/org/highfives/grid/security/JwtUtil.java
로그아웃 시 확인 기능 추가 및 백엔드 쿠키 도메인 설정 추가 
> 로그아웃 확인 추가 

- grid/build/resources/main/org/highfives/grid/approval/query/repository/ApprovalMapper.xml
- grid/src/main/resources/org/highfives/grid/approval/query/repository/ApprovalMapper.xml
> FIX : 휴가 상태 안보이는 문제 해결

- README.md
- grid-f/grid-project/src/views/HumanResources/Profile.vue
- grid/build/resources/main/org/highfives/grid/approval/query/repository/ApprovalMapper.xml
- grid/src/main/resources/org/highfives/grid/approval/query/repository/ApprovalMapper.xml
> Profile 화면 id 분리 

- grid-f/grid-project/src/components/AdTime/AdTimeAdd.vue
> Fix: 캘린더 출장 조회 수정

- grid-f/grid-project/src/components/AdTime/AdTimeAdd.vue
> Fix: 캘린더 날짜 수정

- grid-f/grid-project/src/components/Department/Department.vue
- grid-f/grid-project/src/components/TeamReview/MyReview.vue
- grid-f/grid-project/src/components/TeamReview/ReviewList.vue
fix/wrink-v2 > develop
CSS 수정 및 부서 활성화/비활성화 시 새로고침(조직도 업데이트가 안이루어지는 현상 수정)
> Fix: CSS 수정 및 부서 활성화/비활성화 시 새로고침

- grid-f/grid-project/src/views/HumanResources/AddMulti.vue
> fix : 정보 미입력시 회원 등록 안됨
